sudo: false

language: node_js
node_js:
  - "stable"
  
script:
  - npm install
  - npm run build
  - npm run export
  
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "www.dddeastmidlands.com"
  skip_cleanup: true
  region: eu-west-2
  local_dir: out
  
  on:
    branch: master